// swift-tools-version:5.9
import PackageDescription
import Foundation

// MARK: - Whisper.cpp Path Configuration (Bundled)
// ⚠️ RELEASE 2 ONLY - Audio transcription dependencies
// Uncomment these for Release 2 (January 1st) when audio features are re-enabled

/// Use bundled whisper.cpp library from Vendors directory
/// This makes the project self-contained - no external dependencies needed for building
// let whisperPath = "Vendors/whisper"
// let whisperIncludePath = whisperPath + "/include"
// let whisperLibPath = whisperPath + "/lib"

private struct GeneratedBuildMetadataPayload {
    let version: String
    let buildNumber: String
    let gitCommit: String
    let gitCommitFull: String
    let gitBranch: String
    let buildDate: String
    let forkName: String
}

private let packageRootURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
private let generatedBuildMetadataURL = packageRootURL.appendingPathComponent("UI/BuildMetadata.generated.swift")

writeGeneratedBuildMetadata(at: generatedBuildMetadataURL, projectRootURL: packageRootURL)

private func writeGeneratedBuildMetadata(at url: URL, projectRootURL: URL) {
    let metadata = resolveGeneratedBuildMetadata(projectRootURL: projectRootURL)
    let contents = """
    // Generated by Package.swift. Do not edit manually.
    enum SwiftPMBuildMetadata {
        static let version = \(swiftLiteral(metadata.version))
        static let buildNumber = \(swiftLiteral(metadata.buildNumber))
        static let gitCommit = \(swiftLiteral(metadata.gitCommit))
        static let gitCommitFull = \(swiftLiteral(metadata.gitCommitFull))
        static let gitBranch = \(swiftLiteral(metadata.gitBranch))
        static let buildDate = \(swiftLiteral(metadata.buildDate))
        static let forkName = \(swiftLiteral(metadata.forkName))
    }
    """

    if (try? String(contentsOf: url, encoding: .utf8)) == contents {
        return
    }

    try? contents.write(to: url, atomically: true, encoding: .utf8)
}

private func resolveGeneratedBuildMetadata(projectRootURL: URL) -> GeneratedBuildMetadataPayload {
    let projectYAMLURL = projectRootURL.appendingPathComponent("project.yml")
    let projectYAML = (try? String(contentsOf: projectYAMLURL, encoding: .utf8)) ?? ""

    let version = parseProjectSetting(named: "MARKETING_VERSION", from: projectYAML) ?? "dev"
    let buildNumber = parseProjectSetting(named: "CURRENT_PROJECT_VERSION", from: projectYAML) ?? "unknown"
    let gitCommit = runCommand("/usr/bin/git", arguments: ["rev-parse", "--short", "HEAD"], currentDirectoryURL: projectRootURL) ?? "unknown"
    let gitCommitFull = runCommand("/usr/bin/git", arguments: ["rev-parse", "HEAD"], currentDirectoryURL: projectRootURL) ?? "unknown"
    let gitBranch = runCommand("/usr/bin/git", arguments: ["rev-parse", "--abbrev-ref", "HEAD"], currentDirectoryURL: projectRootURL) ?? "unknown"
    let remoteURL = runCommand("/usr/bin/git", arguments: ["remote", "get-url", "origin"], currentDirectoryURL: projectRootURL) ?? ""

    return GeneratedBuildMetadataPayload(
        version: version,
        buildNumber: buildNumber,
        gitCommit: gitCommit,
        gitCommitFull: gitCommitFull,
        gitBranch: gitBranch,
        buildDate: currentUTCBuildDateString(),
        forkName: normalizeForkName(remoteURL)
    )
}

private func parseProjectSetting(named key: String, from text: String) -> String? {
    for rawLine in text.split(whereSeparator: \.isNewline) {
        let line = rawLine.trimmingCharacters(in: .whitespacesAndNewlines)
        guard line.hasPrefix("\(key):") else { continue }

        let value = line.dropFirst(key.count + 1).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !value.isEmpty else { return nil }

        if value.hasPrefix("\""), value.hasSuffix("\""), value.count >= 2 {
            return String(value.dropFirst().dropLast())
        }

        if value.hasPrefix("'"), value.hasSuffix("'"), value.count >= 2 {
            return String(value.dropFirst().dropLast())
        }

        if let commentIndex = value.firstIndex(of: "#") {
            let trimmed = String(value[..<commentIndex]).trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed.isEmpty ? nil : trimmed
        }

        return String(value)
    }

    return nil
}

private func runCommand(
    _ executable: String,
    arguments: [String],
    currentDirectoryURL: URL
) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: executable)
    process.arguments = arguments
    process.currentDirectoryURL = currentDirectoryURL

    let stdout = Pipe()
    process.standardOutput = stdout
    process.standardError = Pipe()

    do {
        try process.run()
    } catch {
        return nil
    }

    process.waitUntilExit()
    guard process.terminationStatus == 0 else { return nil }

    let data = stdout.fileHandleForReading.readDataToEndOfFile()
    guard let output = String(data: data, encoding: .utf8)?
        .trimmingCharacters(in: .whitespacesAndNewlines),
          !output.isEmpty else {
        return nil
    }

    return output
}

private func normalizeForkName(_ remoteURL: String) -> String {
    var value = remoteURL.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !value.isEmpty else { return "" }

    if let range = value.range(of: "github.com/") {
        value = String(value[range.upperBound...])
    } else if let range = value.range(of: "github.com:") {
        value = String(value[range.upperBound...])
    }

    if value.hasSuffix(".git") {
        value.removeLast(4)
    }

    return value
}

private func currentUTCBuildDateString() -> String {
    let formatter = DateFormatter()
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.timeZone = TimeZone(secondsFromGMT: 0)
    formatter.dateFormat = "yyyy-MM-dd HH:mm:ss 'UTC'"
    return formatter.string(from: Date())
}

private func swiftLiteral(_ value: String) -> String {
    let escaped = value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
        .replacingOccurrences(of: "\n", with: "\\n")
        .replacingOccurrences(of: "\r", with: "\\r")
        .replacingOccurrences(of: "\t", with: "\\t")
    return "\"\(escaped)\""
}

// MARK: - Package Definition

let package = Package(
    name: "Retrace",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .library(name: "Shared", targets: ["Shared"]),
        .library(name: "Database", targets: ["Database"]),
        .library(name: "Storage", targets: ["Storage"]),
        .library(name: "Capture", targets: ["Capture"]),
        .library(name: "Processing", targets: ["Processing"]),
        .library(name: "Search", targets: ["Search"]),
        .library(name: "Migration", targets: ["Migration"]),
        .library(name: "App", targets: ["App"]),
        .library(name: "CrashRecoverySupport", targets: ["CrashRecoverySupport"]),
        .executable(name: "Retrace", targets: ["Retrace"]),
        .executable(name: "RetraceCrashRecoveryHelper", targets: ["RetraceCrashRecoveryHelper"]),
        .executable(name: "TestMostRecentFrame", targets: ["TestMostRecentFrame"]),
        .executable(name: "QueryRewindApps", targets: ["QueryRewindApps"]),
    ],
    dependencies: [
        // NOTE: Dependencies are bundled locally in Vendors/ or will be downloaded at runtime
        // ⚠️ RELEASE 2 ONLY:
        // whisper.cpp - bundled in Vendors/whisper/
        // Models (*.bin, *.gguf) - downloaded at runtime on first launch

        // SQLCipher for reading encrypted Rewind database
        .package(url: "https://github.com/skiptools/swift-sqlcipher.git", from: "1.0.0"),
        // Sparkle for auto-updates
        .package(url: "https://github.com/sparkle-project/Sparkle.git", from: "2.6.0"),
        // SwiftyChrono for natural language date parsing (batmac fork with Swift 5.5+ support)
        .package(url: "https://github.com/batmac/SwiftyChrono.git", revision: "e1bf3bde0f09112909157360b6bf39302f10ae5f")
    ],
    targets: [
        // MARK: - Shared models and protocols
        .target(
            name: "Shared",
            dependencies: [],
            path: "Shared"
        ),

        // MARK: - Database module
        // NOTE: Uses SQLCipher instead of system SQLite3 because Migration module
        // requires SQLCipher for Rewind database, and we can't mix both in one app.
        // SQLCipher works with unencrypted databases too (just don't set PRAGMA key).
        .target(
            name: "Database",
            dependencies: [
                "Shared",
                .product(name: "SQLCipher", package: "swift-sqlcipher")
            ],
            path: "Database",
            exclude: [
                "Tests",
                "README.md",
                "AGENTS.md",
                "PROGRESS.md"
            ]
        ),
        .testTarget(
            name: "DatabaseTests",
            dependencies: ["Database", "Shared"],
            path: "Database/Tests",
            exclude: [
                "_future"  // Release 2+ tests
            ]
            // ⚠️ RELEASE 2 ONLY - Whisper linker settings removed for Release 1
        ),

        // MARK: - Storage module
        .target(
            name: "Storage",
            dependencies: ["Shared"],
            path: "Storage",
            exclude: [
                "Tests",
                "README.md",
                "AGENTS.md",
                "PROGRESS.md"
            ]
        ),
        .testTarget(
            name: "StorageTests",
            dependencies: ["Storage", "Shared"],
            path: "Storage/Tests"
            // ⚠️ RELEASE 2 ONLY - Whisper linker settings removed for Release 1
        ),

        // MARK: - Capture module
        .target(
            name: "Capture",
            dependencies: ["Shared"],
            path: "Capture",
            exclude: [
                "Tests",
                "README.md",
                "AGENTS.md",
                "PROGRESS.md"
            ]
        ),
        .testTarget(
            name: "CaptureTests",
            dependencies: ["Capture", "Shared"],
            path: "Capture/Tests"
            // ⚠️ RELEASE 2 ONLY - Whisper linker settings removed for Release 1
            // ⚠️ RELEASE 2 ONLY - Audio/Tests excluded for Release 1
        ),

        // MARK: - Processing module
        .target(
            name: "Processing",
            dependencies: [
                "Shared",
                "Database"
            ],
            path: "Processing",
            exclude: [
                "Tests",
                "README.md",
                "AGENTS.md",
                "PROGRESS.md"
            ]
            // ⚠️ RELEASE 2 ONLY - Whisper cSettings and linkerSettings removed for Release 1
            // Re-add Accelerate, CoreML, Metal frameworks when audio transcription is re-enabled
        ),
        .testTarget(
            name: "ProcessingTests",
            dependencies: ["Processing", "Shared", "Database", "Storage"],
            path: "Processing/Tests"
            // ⚠️ RELEASE 2 ONLY - Whisper cSettings and linkerSettings removed for Release 1
            // ⚠️ RELEASE 2 ONLY - Audio/Tests excluded for Release 1
        ),

        // MARK: - Search module
        .target(
            name: "Search",
            dependencies: [
                "Shared"
            ],
            path: "Search",
            exclude: [
                "Tests",
                "VectorSearchTODO",  // Exclude vector search implementation
                "README.md",
                "AGENTS.md",
                "PROGRESS.md"
            ]
        ),
        .testTarget(
            name: "SearchTests",
            dependencies: ["Search", "Shared", "Database"],
            path: "Search/Tests"
        ),

        // MARK: - Migration module
        .target(
            name: "Migration",
            dependencies: [
                "Shared",
                .product(name: "SQLCipher", package: "swift-sqlcipher")
            ],
            path: "Migration",
            exclude: [
                "README.md",
                "AGENTS.md",
                "PROGRESS.md"
            ]
        ),

        // MARK: - App integration layer
        .target(
            name: "App",
            dependencies: [
                "Shared",
                "Database",
                "Storage",
                "Capture",
                "Processing",
                "Search",
                "Migration",
                .product(name: "SQLCipher", package: "swift-sqlcipher")
            ],
            path: "App",
            exclude: [
                "Tests",
                "README.md"
            ]
            // ⚠️ RELEASE 2 ONLY - Whisper cSettings and linkerSettings removed for Release 1
        ),
        .testTarget(
            name: "AppTests",
            dependencies: [
                "App",
                "Shared"
            ],
            path: "App/Tests"
            // ⚠️ RELEASE 2 ONLY - Whisper cSettings and linkerSettings removed for Release 1
        ),

        // MARK: - Crash recovery support
        .target(
            name: "CrashRecoverySupport",
            dependencies: [],
            path: "UI/CrashRecoverySupport"
        ),

        // MARK: - UI module
        .executableTarget(
            name: "Retrace",
            dependencies: [
                "Shared",
                "App",
                "Database",
                "Storage",
                "Capture",
                "Processing",
                "Search",
                "Migration",
                "CrashRecoverySupport",
                .product(name: "Sparkle", package: "Sparkle"),
                .product(name: "SwiftyChrono", package: "SwiftyChrono")
            ],
            path: "UI",
            exclude: [
                "CrashRecoveryHelper",
                "CrashRecoverySupport",
                "LaunchAgents",
                "Tests",
                "README.md",
                "AGENTS.md",
                "Info.plist",
                "Retrace.entitlements"
            ],
            resources: [
                .process("Assets.xcassets")
            ]
            // ⚠️ RELEASE 2 ONLY - Whisper cSettings and linkerSettings removed for Release 1
        ),
        .executableTarget(
            name: "RetraceCrashRecoveryHelper",
            dependencies: ["CrashRecoverySupport"],
            path: "UI/CrashRecoveryHelper",
            sources: [
                "main.swift"
            ]
        ),

        // MARK: - Test executable for getMostRecentFrameTimestamp
        .executableTarget(
            name: "TestMostRecentFrame",
            dependencies: [
                "Shared",
                "App"
            ],
            path: "Sources/TestMostRecentFrame"
        ),

        // MARK: - Query Rewind apps utility
        .executableTarget(
            name: "QueryRewindApps",
            dependencies: [
                "Shared",
                .product(name: "SQLCipher", package: "swift-sqlcipher")
            ],
            path: "Sources/QueryRewindApps"
        ),
        .testTarget(
            name: "RetraceTests",
            dependencies: ["Retrace", "CrashRecoverySupport", "Shared", "App"],
            path: "UI/Tests"
            // ⚠️ RELEASE 2 ONLY - Whisper cSettings and linkerSettings removed for Release 1
        ),
    ]
)
