name: Retrace
options:
  bundleIdPrefix: io.retrace
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
  configs:
    Debug:
      SWIFT_COMPILATION_MODE: incremental
      SWIFT_WHOLE_MODULE_OPTIMIZATION: NO
      EMIT_FRONTEND_COMMAND_LINES: YES
      OTHER_SWIFT_FLAGS: "-Xfrontend -enable-implicit-dynamic"
      OTHER_LDFLAGS: "-Xlinker -export_dynamic"
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
      STRIP_INSTALLED_PRODUCT: NO
      COPY_PHASE_STRIP: NO
      STRIP_SWIFT_SYMBOLS: NO
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      ARCHS: arm64

targets:
  Retrace:
    type: application
    platform: macOS
    sources:
      - path: UI
        excludes:
          - Tests
          - README.md
          - AGENTS.md
    dependencies:
      - target: Shared
      - target: App
      - target: Database
      - target: Storage
      - target: Capture
      - target: Processing
      - target: Search
      - target: Migration
      - package: Sparkle
      - package: swift-sqlcipher
        product: SQLCipher
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.app
        INFOPLIST_FILE: UI/Info.plist
        MARKETING_VERSION: "0.6.0"
        CURRENT_PROJECT_VERSION: "5"
        CODE_SIGN_ENTITLEMENTS: UI/Retrace.entitlements
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Developer ID Application"
        DEVELOPMENT_TEAM: 5X5W7C3L9D
        CODE_SIGNING_REQUIRED: YES
        CODE_SIGNING_ALLOWED: YES
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  Shared:
    type: framework
    platform: macOS
    sources:
      - path: Shared
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.Shared

  Database:
    type: framework
    platform: macOS
    sources:
      - path: Database
        excludes:
          - Tests
          - README.md
          - AGENTS.md
          - PROGRESS.md
    dependencies:
      - target: Shared
      - package: swift-sqlcipher
        product: SQLCipher
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.Database

  Storage:
    type: framework
    platform: macOS
    sources:
      - path: Storage
        excludes:
          - Tests
          - README.md
          - AGENTS.md
          - PROGRESS.md
    dependencies:
      - target: Shared
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.Storage

  Capture:
    type: framework
    platform: macOS
    sources:
      - path: Capture
        excludes:
          - Tests
          - README.md
          - AGENTS.md
          - PROGRESS.md
    dependencies:
      - target: Shared
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.Capture

  Processing:
    type: framework
    platform: macOS
    sources:
      - path: Processing
        excludes:
          - Tests
          - README.md
          - AGENTS.md
          - PROGRESS.md
    dependencies:
      - target: Shared
      - target: Database
      - target: Storage
      - target: Search
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.Processing

  Search:
    type: framework
    platform: macOS
    sources:
      - path: Search
        excludes:
          - Tests
          - VectorSearchTODO
          - README.md
          - AGENTS.md
          - PROGRESS.md
    dependencies:
      - target: Shared
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.Search

  Migration:
    type: framework
    platform: macOS
    sources:
      - path: Migration
        excludes:
          - README.md
          - AGENTS.md
          - PROGRESS.md
    dependencies:
      - target: Shared
      - package: swift-sqlcipher
        product: SQLCipher
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.Migration

  App:
    type: framework
    platform: macOS
    sources:
      - path: App
        excludes:
          - Tests
          - README.md
    dependencies:
      - target: Shared
      - target: Database
      - target: Storage
      - target: Capture
      - target: Processing
      - target: Search
      - target: Migration
      - package: swift-sqlcipher
        product: SQLCipher
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.retrace.App

packages:
  swift-sqlcipher:
    url: https://github.com/skiptools/swift-sqlcipher.git
    from: "1.0.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle.git
    from: "2.6.0"
